<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ChouUn.StashMaster.Core.Tests</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <CoreProject Condition="'$(CoreProject)' == ''">../../src/Core/Core.csproj</CoreProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(CoreProject)" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <EmbeddedResource Include="packing-catalog.json" LogicalName="PackingCatalog" />
  </ItemGroup>
</Project>
